### ISSUE TITLE
## Private checklist for PR #39

### ISSUE THREAD

**Issue by ThomasTJdev** [ThomasTJdev/nim_websitecreator#51]
## General
- [x] General UI check
- [x] Files - UI
- [x] Files - Folder (from image)
- [x] Files - Count (#45)
- [x] Plugin - UI
- [x] Plugin - Enable/Disable route
- [x] Docket
- [x] Firejail
- [x] WebP
- [x] Unsplash **I can't get it to work** --> **removed**
- [x] Postgres 
```nim
# Not tested.
# Is "WITHOUT OIDS" required? https://www.postgresql.org/docs/9.6/datatype-oid.html
"Object identifiers (OIDs) are used internally by PostgreSQL as primary keys for various system tables. OIDs are not added to user-created tables, unless WITH OIDS is specified when the table is created, or the default_with_oids configuration variable is enabled. "
```
- [x] DevOps folder
- [x] Datetime2human integration
- [x] Online config
- [x] Admin panel
- [x] Honeypot
- [x] 2FA
- [x] Password generater (random)
- [x] Logs - UI
- [x] Nimble install on a clean system
- [x] Nim latest devel (Error.. hmm.. **Plugin error as mentioned in the comment below, closed**
```nim
Nim Compiler Version 0.19.9 [Linux: amd64] - Compiled at 2019-02-16
nimwc_main.nim(115, 5) Error: cannot generate VM code for pluginsPath = ["/home/user/nim/nim_websitecreator/plugins/contact"]
```
- [x] Check changelog

## Other
- [x] Error using Summernote with Bulma (#37)
- [x] Version bump to 5 **What do you think?**
- [x] History table - purpose? **Well, I added it myself :laughing: Purpose was to keep track on what the users were doing. No purpose at the moment, deletable.**
- [x] -d:noFields - purpose? **deleted**
- [x] `nimwc2fa.nim` - is it needed? Can we delete it?
- [x] TOS
```
Could be expandede? Like https://cxmanager.dk/eula ?
The font didn't work for me. I changed it to font-family sans-serif.
Shouldn't we make it editable? Like the config file. Then the user can specify the details to comply with GDPR.
```

## Future
- [x] `files.tmpl` should use the files-table instead of walkdir on `files/privat-public`. We can then also show how many times, a file has been downloaded. **Agree with comment below, closed**
- [x] 2FA and pwd flow - **Agree with comment below, closed**
```
We should first check pwd and email, if they match we should ask for 2FA. Or we can keep the current layout to force the user to think about 2FA on every login.
```
- [ ] Nim's symlink proc cant overwrite existing symlink (#36)
- [ ] Update NimWC.org with information about all the new features :)

_Originally posted by @ThomasTJdev in https://github.com/ThomasTJdev/nim_websitecreator/pull/39#issuecomment-462368761_

**Comment by juancarlospaco** [comment]
Unsplash:
Works by a Timer, 1 per hour minimum, 1 per 42 days maximum, of continuous running, it needs the config added on the CFG file, like the rest of the config it needs to be valid obviously, you run it and after 1 hour it will change the Background automatically, like many apps to change background on desktop, the CFG on the template has the new configs, the example default values are valid and work.


`"WITHOUT OIDS"` should be removed, my bad.

History Table Purpose:
https://github.com/ThomasTJdev/nim_websitecreator/blob/master/nimwcpkg/resources/administration/createdb.nim#L78-L85 ?
I dunno, you tell me, it was there previously :slightly_smiling_face: 

`nimwc2fa.nim` you can delete it.

Your Nim latest devel Error seems like a Plugin bug.

TOS the problem is that TOS is oriented towards the content of the web you are creating, 
not all TOS are the same, theres no universal TOS, 
web for baby toys should have different TOS than web for adult content as example, 
thats why is almost empty, TOS rarely changes to make it editable online, is up to the user IMHO.

Ok to Bump to 5.

I think the `walk` on the files folder worth it, because Plugins might want to put files there, to be downloaded, and to show up on that list.
`walk` should add files to the table if needed, but remove the `walk` adds no value but might limit plugins on the future, we need a `proc` to Sync `walk` and table.

2FA and Password must be asked to the user every time it need to put the password to Login,
thats the point of the 2FA because it expires every 30 seconds, leaving a potential attacker less than 30 seconds to brute-force the password making it almost impossible.
I want to give a good feeling on security, not like Wordpress that is known as being kinda insecure, and many people avoid using it for that.
[32 CPU PC](https://www.amd.com/en/products/cpu/amd-ryzen-threadripper-2990wx) and 8 Core Raspberry Pi makes forcing Ascii passwords is relatively easy.

**Comment by ThomasTJdev** [comment]
> TOS the problem is that TOS is oriented towards the content of the web you are creating,
> not all TOS are the same, theres no universal TOS,
> web for baby toys should have different TOS than web for adult content as example,
> thats why is almost empty, TOS rarely changes to make it editable online, is up to the user IMHO.
But right now the user can't edit the TOS without editing the file and recompiling?

**Comment by juancarlospaco** [comment]
You are right, maybe it should be a `staticRead` of a simple HTML file, like change it from `*.tmpl` to `*.html`.

**Comment by ThomasTJdev** [comment]
> You are right, maybe it should be a `staticRead` of a simple HTML file, like change it from `*.tmpl` to `*.html`.

Or we could create a table for it?

**Comment by juancarlospaco** [comment]
I dont think it worth it hitting the database for that, it rarely changes, just a string, compile-time or runtime string, but a simple string should do.

Unless you consider it must be a table for some reason that I ignore.
:slightly_smiling_face:

**Comment by ThomasTJdev** [comment]
No, forget the table. I'll go with your suggestion.

**Comment by ThomasTJdev** [comment]
Fixed in #39
